<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_    _processing_of_personal_data</name>
   <tag></tag>
   <elementGuidId>68915195-fcfc-49c2-b2e2-7854aabdcec1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='processing_of_personal_data']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u115-00__control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>processing_of_personal_data</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>processing_of_personal_data</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page-wrapper&quot;]/main[@class=&quot;main-content&quot;]/div[@class=&quot;ui u100-00&quot;]/div[@class=&quot;u100-00__container&quot;]/div[@class=&quot;u100-00__body&quot;]/div[@class=&quot;component-root&quot;]/div[@id=&quot;buy_model_form&quot;]/div[@class=&quot;f101-00__container&quot;]/div[@class=&quot;f101-00__row&quot;]/div[@class=&quot;f101-00__item f101-00-form&quot;]/div[@class=&quot;f101-00-form__container&quot;]/div[@class=&quot;f101-00-form__body&quot;]/form[@id=&quot;buy_model_form&quot;]/div[@class=&quot;form__container&quot;]/div[@class=&quot;form__section&quot;]/div[@class=&quot;form__section-container&quot;]/div[@class=&quot;form-element js-form-field&quot;]/div[@class=&quot;form-element__wrapper&quot;]/div[@class=&quot;form-element__group&quot;]/label[@class=&quot;ui u115-00 required has-focus&quot;]/input[@id=&quot;processing_of_personal_data&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='processing_of_personal_data']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='buy_model_form']/div/div[4]/div/div/div/div/label/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/label/input</value>
   </webElementXpaths>
</WebElementEntity>
